### PR TITLE
Alternative fix for counting Bloom filters

### PR DESCRIPTION
**Pull request by thomasmueller**

### CODE REVIEW

**Comment by lemire** [comment]
This PR does not fix issue 9. Try compiling for a lower target like westmere...

Error output:

```
$ make
g++ -fno-strict-aliasing -Wall -std=c++11 -I. -I../src/ -I../src/bloom/ -I../src/cuckoo/ -I../src/gcs -I../src/gqf/ -I../src/morton/ -I../src/xorfilter -O3 -DNDEBUG -march=native bulk-insert-and-query.cc -o bulk-insert-and-query.exe -Wall
In file included from bulk-insert-and-query.cc:45:0:
../src/bloom/simd-block-fixed-fpp.h: In static member function ‘static __m128i SimdBlockFilterFixed16<HashFamily>::MakeMask(uint64_t)’:
../src/bloom/simd-block-fixed-fpp.h:457:8: error: there are no arguments to ‘_mm_shuffle_epi8’ that depend on a template parameter, so a declaration of ‘_mm_shuffle_epi8’ must be available [-fpermissive]
 return _mm_shuffle_epi8(_mm_set_epi8(1,2,4,8,16,32,64,-128,1,2,4,8,16,32,64,-128),h);
        ^~~~~~~~~~~~~~~~
../src/bloom/simd-block-fixed-fpp.h:457:8: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
../src/bloom/simd-block-fixed-fpp.h: In member function ‘bool SimdBlockFilterFixed16<HashFamily>::Find(uint64_t) const’:
../src/bloom/simd-block-fixed-fpp.h:483:10: error: there are no arguments to ‘_mm_testc_si128’ that depend on a template parameter, so a declaration of ‘_mm_testc_si128’ must be available [-fpermissive]
   return _mm_testc_si128(bucketvalue,mask);
          ^~~~~~~~~~~~~~~
bulk-insert-and-query.cc: In instantiation of ‘Statistics FilterBenchmark(size_t, const std::vector<long unsigned int>&, size_t, const std::vector<long unsigned int>&, size_t, size_t, bool, const std::vector<samples>&, int, bool, bool) [with Table = SimdBlockFilterFixed16<hashing::SimpleMixSplit>; size_t = long unsigned int]’:
bulk-insert-and-query.cc:1427:121:   required from here
bulk-insert-and-query.cc:791:57: error: ‘ConstructFromAddCount’ is not a member of ‘FilterAPI<SimdBlockFilterFixed16<hashing::SimpleMixSplit> >’
   Table filter = FilterAPI<Table>::ConstructFromAddCount(add_count);
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
bulk-insert-and-query.cc:816:29: error: ‘AddAll’ is not a member of ‘FilterAPI<SimdBlockFilterFixed16<hashing::SimpleMixSplit> >’
     FilterAPI<Table>::AddAll(to_add, 0, add_count, &filter);
     ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
bulk-insert-and-query.cc:819:28: error: ‘Add’ is not a member of ‘FilterAPI<SimdBlockFilterFixed16<hashing::SimpleMixSplit> >’
       FilterAPI<Table>::Add(to_add[added], &filter);
       ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
bulk-insert-and-query.cc:860:47: error: ‘Contain’ is not a member of ‘FilterAPI<SimdBlockFilterFixed16<hashing::SimpleMixSplit> >’
       found_count += FilterAPI<Table>::Contain(v, &filter);
                      ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
bulk-insert-and-query.cc:908:31: error: ‘Remove’ is not a member of ‘FilterAPI<SimdBlockFilterFixed16<hashing::SimpleMixSplit> >’
       FilterAPI<Table>::Remove(to_add[added], &filter);
       ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
Makefile:38: recipe for target 'bulk-insert-and-query.exe' failed
make: *** [bulk-insert-and-query.exe] Error 1
```

**Comment by thomasmueller** [comment]
Yes, but this is a different Bloom filter (the SIMD blocked one, simd-block-fixed-fpp), not the counting Bloom filter. So I guess it's an improvement still...

**Comment by lemire** [comment]
Agreed.

**Comment by lemire** [comment]
Merge your PR.

**Pull request merged**
